project:
  type: book

book:
  title: "CHEG 304 Python"
  author: "Kyle Wodehouse"
  date: "5/20/2025"
  chapters:
    - index.qmd
    - pythonfunctionoftheday.ipynb



format:
  html:
    theme: cosmo
    number-sections: false



